name: CI pour l'application Felloway

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repository
        uses: actions/checkout@v4

      - name: Utilisation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installations des dépendances
        run: npm install

      - name: Récupération du numéro de version depuis package.json
        id: get_version
        run: echo "PACKAGE_VERSION=$(node -e "console.log(require('./package.json').version)")" >> $GITHUB_OUTPUT

      - name: Build du projet
        run: npm run build

      - name : Archivage des fichiers de build
        run: zip -r felloway-build-v${{ steps.get_version.outputs.PACKAGE_VERSION }}.zip dist

      - name: Upload de l'artéfact
        uses: actions/upload-artifact@v4
        with: 
          name: felloway-build-v${{ steps.get_version.outputs.PACKAGE_VERSION }}.zip
          path: felloway-build-v${{ steps.get_version.outputs.PACKAGE_VERSION }}.zip

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout du repository
        uses: actions/checkout@v4

      - name: Récupération du numéro de version depuis package.json
        id: get_version
        run: echo "PACKAGE_VERSION=$(node -e "console.log(require('./package.json').version)")" >> $GITHUB_OUTPUT

      - name: Download de l'artificat
        uses: actions/download-artifact@v4
        with:
          name: felloway-build-v${{ steps.get_version.outputs.PACKAGE_VERSION }}.zip
          path: ./

      - name: Creation de la release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.PACKAGE_VERSION }}
          release_name: Felloway Realease v${{ steps.get_version.outputs.PACKAGE_VERSION }}
        
      - name: Upload de la release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: felloway-build-v${{ steps.get_version.outputs.PACKAGE_VERSION }}.zip
          asset_name: felloway-build-v${{ steps.get_version.outputs.PACKAGE_VERSION }}.zip
          asset_content_type: application/zip
  
  deploy:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: Checkout du repository
        uses: actions/checkout@v4

      - name: Récupération du numéro de version depuis package.json
        id: get_version
        run: echo "PACKAGE_VERSION=$(node -e "console.log(require('./package.json').version)")" >> $GITHUB_OUTPUT

      - name: Téléchargement de la release
        uses: actions/download-artifact@v4
        with:
          name: felloway-build-v${{ steps.get_version.outputs.PACKAGE_VERSION }}.zip
          path: ./

      - name: Mis en ligne sur Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FELLOWAY_30160 }}'
          channelId: live
          projectId: felloway-30160
          folder: ./



