name: CI pour l'application Felloway

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repository
        uses: actions/checkout@v4

      - name: Utilisation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installations des dépendances
        run: npm install

      - name: Récupération du numéro de version depuis package.json
        id: get_version
        run: echo ::set-output name=PACKAGE_VERSION::$(node -e "console.log(require('./package.json').version)")


      - name: Build du projet
        run: npm run build

      - name : Archivage des fichiers de build
        run: zip -r felloway-build-v${{ steps.get_version.outputs.PACKAGE_VERSION }}.zip dist

      - name: Upload d'artéfacts
        uses: actions/upload-artifact@v4
        with: 
          name: felloway-build-v${{ steps.get_version.outputs.PACKAGE_VERSION }}
          path: felloway-build-v${{ steps.get_version.outputs.PACKAGE_VERSION }}.zip


